-- Shared demo catalog. Seed once; preserve subsequent editor changes.
insert into public.song_catalog (id,title,artist,category,difficulty,age_level,bpm,duration_sec,emoji,color,pattern,description,builtin_audio_id,rights_status,rights_note,published,sort_order) values
('garden-hello','בוקר של צלילים','הביט של הגן · קטע מקורי ללא שירה','movement','easy','3-6',100,19.2,'☀️','#FFA500',array['red','rest','yellow','rest'],'מתחילים בפעימה קבועה, ומצטרפים במחיאה בכל פעימה שנייה.','garden-hello','cleared','Original instrumental score authored for the Habeat demo; no third-party recording.',true,0),
('rain-dance','טיפות רוקדות','הביט של הגן · קטע מקורי ללא שירה','nature','easy','3-6',80,24,'💧','#00B4E6',array['purple','rest','blue','rest'],'מקשיבים לטיפות, מנגנים בעדינות ומשאירים מקום לשקט.','rain-dance','cleared','Original instrumental score authored for the Habeat demo; no third-party recording.',true,1),
('color-parade','מצעד הצבעים','הביט של הגן · קטע מקורי ללא שירה','movement','easy','3-6',120,16,'🌈','#8B5CF6',array['red','yellow','purple','rest'],'מעבירים את הפעימה בין שלושה כלים ועוצרים יחד בהפסקה.','color-parade','cleared','Original instrumental score authored for the Habeat demo; no third-party recording.',true,2),
('im-ata-sameach','אם אתה שמח','שיר מוכר · קובץ שמע טרם נוסף','movement','easy','3-6',120,null,'😊','#FFD600',array['red','yellow','red','blue'],'פריט לתכנון הספרייה. השמעה תיפתח לאחר הוספת הקלטה מאושרת לשימוש.',null,'pending',null,true,3),
('yonatan-hakatan','יונתן הקטן','שיר מוכר · קובץ שמע טרם נוסף','animals','medium','3-5',108,null,'🐑','#8B5CF6',array['purple','red','yellow','blue'],'פריט לתכנון הספרייה. השמעה תיפתח לאחר הוספת הקלטה מאושרת לשימוש.',null,'pending',null,true,4),
('ledavid-moshe','לדוד משה הייתה חווה','שיר מוכר · קובץ שמע טרם נוסף','animals','hard','4-6',100,null,'🐄','#22C55E',array['red','yellow','red','yellow','blue','red','yellow','green'],'פריט לתכנון הספרייה. השמעה תיפתח לאחר הוספת הקלטה מאושרת לשימוש.',null,'pending',null,true,5),
('yadayim-lemaala','ידיים למעלה','שיר מוכר · קובץ שמע טרם נוסף','movement','easy','3-5',130,null,'🙌','#FF4DA6',array['red','yellow','red','yellow'],'פריט לתכנון הספרייה. השמעה תיפתח לאחר הוספת הקלטה מאושרת לשימוש.',null,'pending',null,true,6),
('ken-latzipor','קן לציפור','שיר מוכר · קובץ שמע טרם נוסף','nature','medium','4-6',96,null,'🐦','#00B4E6',array['green','blue','green','blue','yellow','rest'],'פריט לתכנון הספרייה. השמעה תיפתח לאחר הוספת הקלטה מאושרת לשימוש.',null,'pending',null,true,7)
on conflict (id) do nothing;
