import {chromium} from 'playwright'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import {resolve} from 'node:path'
const base=process.env.PREVIEW_TEST_URL
const output=resolve(process.env.SCREEN_CAPTURE_DIR||'test-results/screen-map')
mkdirSync(output,{recursive:true})
const version=await (await fetch(base+'/build-info.json')).json()
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']})
const browserVersion=browser.version()
const captures=[]
const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true})
const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message))
await page.route('https://oqwzjhqzjfhdlploezad.supabase.co/**',route=>route.fulfill({status:503,body:'controlled offline fixture; no backend request'}))
async function go(path){await page.goto(base+path);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(1300)}
async function shot(id,title,audience,note=''){
 await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(250)
 const file=`${id}.png`;await page.screenshot({path:resolve(output,file),fullPage:true})
 captures.push({id,title,audience,note,route:new URL(page.url()).pathname+new URL(page.url()).search,file,viewport:{width:390,height:844},fullPage:true,
  links:await page.locator('a[href]').evaluateAll(nodes=>nodes.map(a=>({label:a.innerText||a.getAttribute('aria-label'),href:a.getAttribute('href')})))})
}
await go('/');await shot('01-home','מסך הבית','משותף','אין כיום הפרדת הרשאות בין ניווט ילד וגננת.')
await go('/library');await page.waitForFunction(()=>!document.body.innerText.includes('טוענים'))
await shot('02-library','ספריית השירים','ילד','בדיקת תוכנה עם חסימת בקשות לשרת: שלושת קטעי ההתנסות המקוריים זמינים מקומית.')
await page.getByRole('button',{name:'הקרא שוב: ההסבר על בוקר של צלילים',exact:true}).click()
await page.waitForFunction(()=>document.querySelector('[data-active-word="true"]'))
await shot('03-library-reading','הקראה מסונכרנת בספרייה','ילד','קובץ MP3 המקורי; הצילום נעשה בזמן ניגון, ללא שינוי שעון הנגן.')
await go('/magic-song')
for(let q=1;q<=10;q++){
 await page.locator(`[data-narration="question-${q}"]`).waitFor();await page.waitForTimeout(400)
 await shot(`magic-${q}`,`שיר הקסם — שאלה ${q}`,'ילד')
 if(q<10)await page.locator('[role="button"]').first().click()
}
await page.getByPlaceholder('לדוגמה: שמיים, ניצוץ, ריחוף...').fill('ניצוץ')
await page.getByRole('button',{name:'צרו מילים לשיר!',exact:true}).click()
await page.getByText('המילים לשיר שלכם 🎵',{exact:true}).waitFor()
await shot('magic-result','שיר הקסם — מילים וליווי לניסיון','ילד','ליווי מקורי קיים, ללא קול שר וללא התאמה למילים; אין הקלטת שירה אישית.')
await go('/guide');await shot('guide-child','הדרכה לילדים','ילד')
await page.getByRole('button',{name:'לגננות 👩‍🏫',exact:true}).click();await shot('guide-teacher','הדרכה לגננות','גננת')
await go('/recording');await shot('recording-audio','אולפן — הקלטת קול','משותף','מצב התחלתי. אין כאן בדיקת מיקרופון פיזי.')
await page.getByRole('button',{name:'🎬 וידאו',exact:true}).click();await shot('recording-video','אולפן — הקלטת וידאו','משותף','מצב התחלתי. מצלמה לא הופעלה.')
await go('/teacher');await shot('teacher','מצב גננת','גננת','נתוני הילדים והתחנות הם נתוני הדגמה קיימים.')
await go('/beat-manager');await shot('beat-manager','מנהל הביט','גננת','טיימר ונתוני פעילות להדגמה; אינם חיבור ציוד.')
await page.getByRole('button',{name:'שנה',exact:true}).click();await shot('beat-song','מנהל הביט — בחירת שיר','גננת','בחירת נתון הדגמה אינה פרסום הקלטת שיר מוכר.')
// The existing selectable song card is a div, not an accessible button.
const songTitle=await page.locator('.font-black').allTextContents()
const firstSong=page.locator('div[style*="cursor: pointer"]').first()
await firstSong.click();await page.getByText('עקבי אחרי הצבעים',{exact:true}).waitFor();await shot('beat-rhythm','מנהל הביט — תרגול קצב','גננת','תרגול צבעים קיים, ללא אימות נגינה מהכלי.')
await page.getByRole('button',{name:'המשך לבחירת כלים ←',exact:true}).click();await shot('beat-instruments','מנהל הביט — בחירת כלים','גננת','בחירת כלי ברשימה אינה זיהוי התקן פיזי.')
await go('/stations');await shot('stations','תחנות נגינה','גננת','נתוני תחנות להדגמה.')
await go('/behind-scenes');await shot('behind-scenes','מאחורי הקלעים','משותף')
await go('/dashboard');await shot('dashboard','דאשבורד עירוני','גננת','נתוני הדגמה; אין להסיק פעילות אמת מהמדדים.')
await go('/turn-taking');await shot('input-disconnected','משחק — ללא כלי מחובר','ילד','הגדרות המבוגר סגורות; לא התבקשה הרשאת ציוד ואין יחידה פיזית מחוברת.')
await page.getByRole('button',{name:'הגדרות כלי למבוגר',exact:true}).click()
await page.getByLabel('מקור קלט').selectOption('simulation')
await page.getByRole('button',{name:'סיימנו לכוון, חוזרים למשחק',exact:true}).click()
await shot('turn-sim-ready','משחק — הדמיה מוכנה','ילד','הדמיית תוכנה בלבד. ההנחיה היא של פעולה אחת.')
await page.getByRole('button',{name:'התחילו',exact:true}).click();await page.locator('[data-turn="waiting"]').waitFor()
await shot('turn-sim-wait','משחק — תור הילד','ילד','הדמיה; לאחר צליל הדגמה אחד.')
await page.getByRole('button',{name:'פעולת הדמיה',exact:true}).click();await shot('turn-sim-one','משחק — נקלטה פעולה אחת','ילד','אירוע אחד משלים משימת פעולה אחת; דיוק קצבי אינו נמדד.')
await page.getByRole('button',{name:'הגדרות כלי למבוגר',exact:true}).click()
await page.getByLabel('רמת הסבב').selectOption('2')
await page.getByRole('button',{name:'סיימנו לכוון, חוזרים למשחק',exact:true}).click()
await page.getByRole('button',{name:'התחילו',exact:true}).click();await page.locator('[data-turn="waiting"]').waitFor()
await page.getByRole('button',{name:'פעולת הדמיה',exact:true}).click();await shot('turn-sim-two-partial','משחק — פעולה ראשונה מתוך שתיים','ילד','הפעולה נקלטה, אך המשימה עדיין לא הושלמה.')
await page.getByRole('button',{name:'פעולת הדמיה',exact:true}).click();await shot('turn-sim-two-complete','משחק — שתי פעולות','ילד','הושלם מספר פעולות; אין טענה לדיוק בקצב או לחומרה.')
await page.getByRole('button',{name:'הגדרות כלי למבוגר',exact:true}).click()
await page.getByText('אבחון ושמירת דוח למבוגר',{exact:true}).click()
await shot('input-simulation-log','אבחון — יומן הדמיה מלא','גננת','שדות הציוד מציינים יעד מתוכנן בלבד; זו הדמיה ללא כלי. זמני הדפדפן אינם השהיה פיזית.')
await browser.close()
if(errors.length)throw Error(errors.join('\n'))
writeFileSync(resolve(output,'manifest.json'),JSON.stringify({version,browser:`Chromium ${browserVersion} / Playwright 1.62.1`,capturedAt:new Date().toISOString(),physicalDeviceTest:false,captures},null,2))
console.log(`Captured ${captures.length} full-page states from ${version.version}: ${output}`)
